# Description of what this change includes:
# Fixed CloudFormation validation errors by correcting AWSTemplateFormatVersion, Resources spelling,
# S3 resource type, properly nesting BucketPolicy under Resources, fixing indentation, and
# correcting policy resource ARN to use !Sub with /* for public GetObject access.
#
# Revision number:
# Rev 1.0
#
# Date:
# February 17, 2026AWSTemplateFormatVersion: '2010-09-09'
Description: S3 static website hosting with public read access (lab style)

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3 (HTTP)
    Value: !GetAtt S3Bucket.WebsiteURL

  S3BucketSecureURL:
    Description: S3 bucket REST endpoint (HTTPS, not the website endpoint)
    Value: !Sub 'https://${S3Bucket.DomainName}'

